#working
apiVersion: v1
kind: Service
metadata:
  name: ms-mongo
spec:
  ports:
  - port: 27017
  selector:
    app: ms-mongo
  clusterIP: None
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ms-mongo-deploy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-mongo
    spec:
      containers:
      - name: ms-mongo
        image: jadatravu/mservice-ms-mongo
        ports:
        - containerPort: 27017
          hostPort: 27017

