# Generated by Django 2.2.4 on 2019-10-14 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='code',
            field=models.CharField(max_length=20),
        ),
    ]
