# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-05 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecretModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normal_value', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('encrypted_value', models.CharField(max_length=255)),
            ],
        ),
    ]
